textroll_sinwave:
                dc.w 4
                dc.w 4
                dc.w 5
                dc.w 5
                dc.w 6
                dc.w 6
                dc.w 6
                dc.w 6
                dc.w 7
                dc.w 6
                dc.w 6
                dc.w 6
                dc.w 6
                dc.w 5
                dc.w 5
                dc.w 4
                dc.w 4
                dc.w 3
                dc.w 2
                dc.w 2
                dc.w 1
                dc.w 1
                dc.w 1
                dc.w 1
                dc.w 1
                dc.w 1
                dc.w 1
                dc.w 1
                dc.w 1
                dc.w 2
                dc.w 2
                dc.w 3

textroll_table_size                dc.w  64
