textroll_sinwave:
                dc.w 0
                dc.w 0
                dc.w 0
                dc.w 1
                dc.w 1
                dc.w 1
                dc.w 2
                dc.w 2
                dc.w 2
                dc.w 2
                dc.w 2
                dc.w 2
                dc.w 3
                dc.w 2
                dc.w 2
                dc.w 2
                dc.w 2
                dc.w 2
                dc.w 2
                dc.w 1
                dc.w 1
                dc.w 1
                dc.w 0
                dc.w 0

textroll_table_size                dc.w  48
